src/accounts/_api/urls.py
from accounts.api.views import registration

from django.urls import path

app_name = 'account'

urlpatterns = [
    path('registration/', registration, name='registration'),


]

src/accounts/urls.py
from accounts.views import AccountCreateView

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('', AccountCreateView.as_view(), name='register'),

]

src/posts/api/urls.py
from django.urls import path

from posts.api.views import (
    CommentCreateView,
    CommentListUpdateDeleteView,
    PostActionCreateView,
    PostListCreateView,
    PostListUpdateDeleteView,
    PostListView,
)

app_name = 'api_post'

urlpatterns = [
    path('post/list/', PostListView.as_view(), name='posts-list'),
    path('post/create/', PostListCreateView.as_view(), name='posts-create'),
    path('post/update/<int:pk>/', PostListUpdateDeleteView.as_view(), name='post_update'),
    path('comment/create/', CommentCreateView.as_view(), name='posts-list'),
    path('comment/update/<int:pk>/', CommentListUpdateDeleteView.as_view(), name='test-detail'),
    path('post/upvote/', PostActionCreateView.as_view(), name='upvote'),
]

src/rest_api/urls.py
from django.contrib import admin
from django.urls import include, path

API_PREFIX = 'api/v1'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),

    path(f'{API_PREFIX}/', include('posts.api.urls')),
    path(f'{API_PREFIX}/api-auth/', include('rest_framework.urls')),
    path(f'{API_PREFIX}/auth/', include('djoser.urls')),
    path(f'{API_PREFIX}/auth_token/', include('djoser.urls.authtoken')),
]

handler404 = 'rest_api.views.error_404'
handler500 = 'rest_api.views.error_500'
handler403 = 'rest_api.views.error_403'
handler400 = 'rest_api.views.error_400'

src/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

src/posts/models.py
from accounts.models import User

from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=64)
    link = models.URLField(max_length=200)
    create_date = models.DateTimeField(null=True, auto_now_add=True)
    author = models.ManyToManyField(to=User, related_name='posts')

    def __str__(self):
        return f'{self.title}'


class Comment(models.Model):
    content = models.TextField(max_length=200)
    create_date = models.DateTimeField(null=True, auto_now_add=True)
    user = models.ForeignKey(to=User, related_name='comments', on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'


class PostAction(models.Model):
    class POST_ACTION_TYPES(models.IntegerChoices):
        DISLIKE = -1, "Dislike"
        LIKE = 1, "Like"

    upvotes = models.IntegerField(choices=POST_ACTION_TYPES.choices, default=0)
    user = models.ForeignKey(to=User, related_name='postaction', on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, related_name='postaction', on_delete=models.CASCADE)

src/accounts/forms.py
from accounts.models import User

from django.contrib.auth.forms import UserCreationForm


class AccountCreateForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'password1', 'password2']

src/accounts/_api/views.py
from accounts.api.serializers import UserSerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response


@api_view(['POST', ])
def registration(request):
    if request.method == 'POST':
        serializer = UserSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            data['response'] = "successfully registered a new user."
            data['username'] = user.username
        else:
            data = serializer.errors
        return Response(data)

src/accounts/views.py
from accounts.forms import AccountCreateForm
from accounts.models import User

from django.views.generic import CreateView


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = "/api/v1/api-auth/login/"

src/posts/api/views.py
from django.db.models import Sum

from posts.api.permissions import CommentOwnerOrReadOnly, PostOwnerOrReadOnly
from posts.api.serializers import CommentSerializer, PostActionSerializer, PostListSerializer, PostUpdateSerializer
from posts.models import Comment, Post, PostAction

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated


class PostListView(generics.ListAPIView):
    queryset = Post.objects.all().annotate(
        total_upvotes=Sum('postaction__upvotes')
    )
    serializer_class = PostListSerializer
    permission_classes = (IsAuthenticated,)


class PostListCreateView(generics.CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostUpdateSerializer


class PostListUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostUpdateSerializer
    permission_classes = (PostOwnerOrReadOnly,)


class CommentCreateView(generics.ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class CommentListUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (CommentOwnerOrReadOnly,)


class PostActionCreateView(generics.ListCreateAPIView):
    queryset = PostAction.objects.all()
    serializer_class = PostActionSerializer

src/posts/views.py
from django.shortcuts import render # noqa

# Create your views here.

src/rest_api/views.py
from django.shortcuts import render


def error_400(request, exception):
    data = {}
    return render(request, 'errs/400.html', data)


def error_404(request, exception):
    data = {}
    return render(request, 'errs/404.html', data)


def error_403(request, exception):
    data = {}
    return render(request, 'errs/403.html', data)


def error_500(request):
    data = {}
    return render(request, 'errs/500.html', data)

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title> Register new user </title>
{% endblock  %}


{% block subheader %}
<header>Register new user</header>
{% endblock  %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input class="btn btn-outline-dark" type="submit" value="Register">

    </form>
{% endblock %}

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block title %}
    <title> Testify </title>
{% endblock  %}
{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock  %}
</head>
<body>


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

  <a class="navbar-brand" href="{% url 'accounts:register' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <a class="nav-link" href="/api/v1/api-auth/login/">Login<span class="sr-only">(current)</span></a>
      </li>


<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--      </li>-->
    </ul>
   <ul class="navbar-nav ">
            <li class="nav-item active">
               <a class="nav-link" href="{% url 'accounts:register' %}">Sign up</a>
           </li>


    </ul>
  </div>
</div>
</nav>
{% endblock  %}

<div class="container">


{% block header %}
<div class="border border-success shadow-lg p-3 mb-5 m-3 bg-white rounded text-center display-4">
{% block subheader %}
    <header>
    Headers
    </header>
{% endblock  %}
</div>
{% endblock  %}

{% block content %}
{% endblock  %}

</div>
</body>
</html>